# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-08 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.UUIDField(default='3385b4b118dd431280245bc13cf8a752', primary_key=True, serialize=False),
        ),
    ]
