# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-11 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20170409_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='choices',
            field=models.CharField(choices=[('A', 'approved'), ('P', 'pending'), ('R', 'rejected')], default='pending', max_length=8),
        ),
    ]
