# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 05:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import lobby.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('content', models.TextField()),
            ],
            bases=(lobby.models.CreatedAtModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_email', models.CharField(max_length=255)),
                ('content', models.TextField()),
            ],
            bases=(lobby.models.CreatedAtModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('blogpost', models.ManyToManyField(related_name='tags', to='lobby.BlogPost')),
            ],
        ),
    ]
