# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-16 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0003_comment_blogpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='blogpost',
            field=models.ManyToManyField(blank=True, null=True, related_name='tags', to='lobby.BlogPost'),
        ),
    ]
