# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-17 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0004_auto_20170316_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='blogpost',
            field=models.ManyToManyField(related_name='tags', to='lobby.BlogPost'),
        ),
    ]
