# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 16:43
from __future__ import unicode_literals

from django.db import migrations

def tbd(apps, schema_editor):
    User = apps.get_model('everything', 'User')

class Migration(migrations.Migration):

    dependencies = [
            # ('users', '0001_initial'),
            ('everything', '0003_auto_20170425_1622'),

    ]

    operations = [
            migrations.RunPython(tbd),
    ]
