# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 04:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lobby', '0003_auto_20170324_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
