# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 23:56
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0002_auto_20170505_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofile',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
