# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 11:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_offer_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='choices',
            field=models.CharField(choices=[('A', 'approved'), ('P', 'pending'), ('R', 'rejected')], default='A', max_length=8),
        ),
    ]
