# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 17:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('everything', '0003_auto_20170425_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='users.User'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='users.User'),
        ),
        migrations.AlterField(
            model_name='product',
            name='comments',
            field=models.ManyToManyField(through='everything.Comment', to='users.User'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
